# Generated by Django 5.2.12 on 2026-03-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('vehicles', '0002_fuelusage_maintenancerecord_vehicletracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='vehicles.vehicle'),
        ),
    ]
