# Generated by Django 5.2.10 on 2026-01-24 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site_engineers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'SITE_ENGINEER'}, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
