# Generated by Django 5.2.11 on 2026-06-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='theme_color',
            field=models.CharField(default='#4f46e5', max_length=7),
        ),
    ]
